### ISSUE TITLE
Doesn't have translations

### ISSUE THREAD

**Issue by seb128** [filip-dobrocky/2048#2]
It would be nice if the game was translatable ;-)

**Comment by ghost** [comment]
Hello,
Could you please make this app translatable?
Thanks for this great work!

**Comment by ghost** [comment]
Thank you very much!!!
Have you ever considered to host the translations in [Launchpad](https://wiki.ubuntu.com/Translations/LpProjectConfiguration), this way the translations could be more easily reviewed by Ubuntu Translators?

**Comment by filip-dobrocky** [comment]
I'll look into it, but I don't have much free time. I have yet to figure out how many things work now, because so much has changed since I last developed for ubuntu. I'm not sure if I'll be able to maintain this properly. Thank you for your effort, though.
